import { Request, BaseDto, Appointment } from '../lib/index';
import { UserDto } from 'src/users/users.dto';

export class RequestDto extends BaseDto implements Request {
  constructor(request: Request) {
    super(request);

    this.zip = request.zip;
    this.deliveryTime = request.deliveryTime;
    this.whereToSell = request.whereToSell;
    this.noOfItems = request.noOfItems;
    this.typeOfItems = request.typeOfItems;
    this.itemsSizes = request.itemsSizes;
    this.itemQualities = request.itemQualities;
    this.itemlocation = request.itemlocation;
    this.needRealtor = request.needRealtor;
    this.pressureWashItems = request.pressureWashItems;
    this.state = request.state;
    this.city = request.city;
    this.movingFrom = request.movingFrom;
    this.movingFromFloor = request.movingFromFloor;
    this.movingTo = request.movingTo;
    this.movingToFloor = request.movingToFloor;
    this.extraItem = request.extraItem;
    this.organized = request.organized;
    this.requestType = request.requestType;
    this.leads = request.leads;
    this.leadPrice = request.leadPrice;
    this.images = request.images;
    this.videos = request.videos;
    this.remark = request.remark;
    this.requesterOwner = request.requesterOwner;
    this.hiredAffiliate = request.hiredAffiliate;
    this.price = request.price;
    this.status = request.status;
    this.status = request.status;
    this.isActive = request.isActive;
    this.items = request.items;
    this.realtorConnectedWith = request.realtorConnectedWith;
    this.affiliateNotes = request.affiliateNotes;
    this.affiliateImages = request.affiliateImages;
    this.affiliateVideos = request.affiliateVideos;
    this.jobDate = request.jobDate;
    this.endDate = request.endDate;
    this.whatHelpNeed = request.whatHelpNeed;
    this.itemsWeight = request.itemsWeight;
    this.isFinalized = request.isFinalized;
    this.appointments = request.appointments;
    this.jobUpdates = request.jobUpdates;
  }

  zip: string;
  deliveryTime: string;
  whereToSell: string;
  noOfItems: string;
  typeOfItems: Object;
  itemsSizes: Array<any>;
  itemQualities: Array<any>;
  itemlocation: Object;
  needRealtor: string;
  pressureWashItems: Object;
  state: string;
  city: string;
  movingFrom: Array<string>;
  movingFromFloor: number;
  movingTo: Array<string>;
  movingToFloor: number;
  extraItem: string;
  organized: Object;
  images: Array<any>;
  videos: Array<any>;
  remark: string;
  requesterOwner?: UserDto;
  price: number;
  status?: string;
  isActive?: string;
  hiredAffiliate?: UserDto;
  requestType: string;
  leads?: Array<any>;
  leadPrice?: number;
  items?: Array<any>;
  realtorConnectedWith?: string;
  affiliateNotes?: string;
  affiliateImages?: Array<string>;
  affiliateVideos?: Array<string>;
  jobDate?: Date;
  endDate?: Date;
  whatHelpNeed?: string;
  itemsWeight?: string;
  isFinalized: boolean;
  appointments: Appointment[];
  jobUpdates: Array<any>;
}
